feat: Include on demand delivery process
spartansolutions/Plugin-National-Grid pull request #6
Opened 2022-03-22 16:26 UTC by stephen-spartan

For future reference should or shouldn't I include the altered json file?

2022-03-22 16:54 UTC, neil-spartan requested changes
Will wait till full functionality is implemented before reviewing the process itself, but had a couple of small comments.

2022-03-22 16:54 UTC, neil-spartan commented on src/plugin/mobile/processConfig/processes/onDemandDeliveryWorkDataProcessConfig.ts
> +export default onDemandDeliveryWorkDataProcessConfig
Don't need this file since the config is empty.

2022-03-22 16:54 UTC, neil-spartan commented on src/plugin/mobile/processRegister.ts
> +    {
Elsewhere the indentation is 2 spaces. We should probably add eslint or workspace settings to control this, but in the meantime can you change your editor settings to use 2 spaces for indentation and correct wherever it is currently 4?

2022-03-24 13:36 UTC, stevenmldn commented on src/plugin/mobile/processes/onDemandDeliveryWorkDataProcess.ts
> +declare module '../../../types/mobile' {
Did we work out what this does? I thought we removed this on the last review?

2022-03-24 13:37 UTC, stevenmldn commented on src/plugin/mobile/processes/onDemandDeliveryWorkDataProcess.ts
> +}
What are these two interface definitions are adding?  Are they used?

2022-03-24 13:40 UTC, stevenmldn commented on src/plugin/mobile/processes/onDemandDeliveryWorkDataProcess.ts
> +          this.navigate('selected', { ownerMetadata })
What is the `selected` method doing here here, why are you overriding the default behavior? I showed you an wayt involving less code to achieve what you are trying to do when we last looked at this.

2022-03-25 17:13 UTC, stevenmldn commented on src/plugin/mobile/processes/onDemandDeliveryWorkDataProcess.ts
> +              return session.metadataService.getByPartialValue('requesterMetadata', value, 25)
Can you remove the word 'Metadata' from the Metadata.Category, so it would just be requested. Could you do this for all metadata configs, (need to update the customer-Config repo as well

2022-03-25 17:15 UTC, stevenmldn commented on src/plugin/mobile/processes/onDemandDeliveryWorkDataProcess.ts
> +          return jQuery.resolve<DataOut>({ 'WorkAndDispatchResults': dataformHelper.toJSON(dataformResults) })
I see we are calling toJson here and in the 'OutputOnDemandData' step. Do we need to do it in both places? I would have expected it in the 'OutputOnDemandData' step but not here

2022-03-25 17:17 UTC, stevenmldn commented on src/types/shared/domainTypes.ts
> +export interface DataformTask {
I Think we need to use inheritance/composition to create these types. Like there should be a Task type which defines Id, and this inherits from it

2022-04-08 11:35 UTC, merged